### ISSUE TITLE
[IDEA] Make self-hosting easier

### ISSUE THREAD

**Issue by albertodvp** [andretkachenko/nexus-bot#164]
First of all, thank you for your work. :pray: 

We are currently using your bot in our discord server self-hosting it.
The self-host process was not straightforward. We made it work with `docker` and `docker-compose` so we can easily replicate it.

I could open a pull request as soon as I finish some proper documentation about the setup. I changed nothing in the code. You can see my fork if you need more information.

Are you interested in this feature?

I would take this opportunity to ask you which version of `npm` and `node` are you using

Thank you for your time

**Comment by andretkachenko** [comment]
Hi @albertodvp 
First, thank you for your kind words.
I'm actually surprised that someone actually decided to self-host the bot. And I'm even more surprised by your words about hard deploy - it's actually a standard deploy flow typical for TS/NodeJS applications - [that's why the wiki page about it takes just 6 steps](https://github.com/andretkachenko/nexus-bot/wiki/Environment-setup)
Regarding the version - I'm using exactly the same versions that are stated in package.json. Currently, it's  `16.15.0` for _node_ and `8.5.5` for _npm_, and I believe I updated them twice, following upgrades of the DiscordJS library.
Regarding docker image - that would be great, feel free to open a pull request whenever you're feeling it.

**Comment by andretkachenko** [comment]
To sate my curiosity, could you please tell me why you decided to go with the self-hosting option? I see no big benefit in doing this without making any changes or extensions. (You can actually skip this question if you want to keep it secret)

**Comment by albertodvp** [comment]
> To sate my curiosity, could you please tell me why you decided to go with the self-hosting option? I see no big benefit in doing this without making any changes or extensions. (You can actually skip this question if you want to keep it secret)

Well, not very interesting reasons here :sweat_smile:

People were complaining about downtimes, there weren't crazy ones but, you know, non-tech people have difficulties in understanding the complexities of software systems. 

I took this opportunity to play a bit with your tool, it was quite educational for me play because I had never "deployed" a discord bot, you made a great job but I had to pack something even easier to set up and replicate by non-tech people with very few requirements (namely, only `docker`)

**Comment by andretkachenko** [comment]
Oh, I got it.
Yup, these downtimes were annoying - Discord decided to change their API right around the time I had to leave Kyiv.
That's actually the last time I upgraded npm for the project - when I upgraded the DiscordJS library to the version that contains a fix.
Plus, Heroku got into trouble with GitHub integration secrets, which also didn't help.
FYI: the issue is already fixed, deployed like a month ago, and actually pushed to this repo around 4 days, right after I returned back home.

**Comment by andretkachenko** [comment]
Yeah, docker is great stuff, I like it as well. Never needed to have it for me, but an already-prepared docker config would be cool to have.

**Comment by albertodvp** [comment]
Ok, I pushed our complete version. I had to do some minor changes that are less interesting for you. I will open a PR only with the `Dockerfile`, if you are curious and find that our "setup", if properly tuned, could add vaule to this repo we could talk about merging the work I made there.

In any case, thank you for sharing this and for your precious time. I hope you and your loved ones are fine and also hope some easier time will come soon :heart:

**Comment by andretkachenko** [comment]
Hi @albertodvp 
Not sure if you're receiving notifications from your PR, so decided to write here as well.
I've reviewed your PR. No objections for dockerfile itself, but you've created your branch from master, but I use it only to deploy the bot. Could you please remake this PR to target develop?

**Comment by andretkachenko** [comment]
Great, thank you very much for your work!
